### PR TITLE
fix: 🐛 use of the package in browsers

### PR DESCRIPTION
**Pull request by ottonielmatheus**
closes: #93

An export problem that occurs when using the package by `bower` in the browser makes it useless to use it in browsers.

There is a validation to identify whether the environment is `server-side` or `client-side` in the file, but before this file is exported, it tries to use `module.exports` and `require`, as it does not have validation in the `index.js` file, at a time, it breaks and makes it impossible to use the package in the browser.

The fix is simple, but it changes structure, it is necessary that `index.js` be the old file `lib/schema-inspector.js`.

### CODE REVIEW

**Comment by lfreneda** [comment]
@Atinux It would be great :)

**Comment by ViniciusFXavier** [comment]
My fear is that there may be people who are pointing to the file as shown in the DOC, if you make this change of file location it can break for people.

image

### It is very complicated to move the file.
### I don't think that would be correct.

An alternative would be to change both `package.json` and `bower.json`.
Change `"main": "index.js"`, to `"main": "./lib/schema-inspector.js"`.

**Comment by ViniciusFXavier** [comment]
Or perhaps the best option is to change the `index.js` to better detect whether it is NodeJs or Browser.

**Comment by mattwelke** [comment]
I'm going to need someone with Bower expertise to take a look at this issue. I have no experience at all with Bower and not enough time to learn it right now. If someone can take a look at this and post proof that a particular change fixes Bower imports, I can merge it in.

Is this an issue that just came up with 2.0.0 or has this always been an issue? We never had anyone complaining about usage with Bower in 1.x.x.

**Comment by mattwelke** [comment]
Also note that @Atinux is no longer a maintainer of this library.

**Comment by ViniciusFXavier** [comment]
Add this to `index.js` must fix the module import.

```js
(function () {
    var root = this; 
    var SchemaInspector = new Object();

    if (typeof module !== 'undefined' && module.exports) {
        SchemaInspector = require('./lib/schema-inspector');
        module.exports = SchemaInspector;
    }
    root.SchemaInspector = SchemaInspector;
})();
```

When doing this will not broken.
```html
<script type="text/javascript" src="bower_components/schema-inspector/lib/schema-inspector.js"></script>
```

**Comment by ViniciusFXavier** [comment]
> I'm going to need someone with Bower expertise to take a look at this issue. I have no experience at all with Bower and not enough time to learn it right now. If someone can take a look at this and post proof that a particular change fixes Bower imports, I can merge it in. @ViniciusFXavier it looks like you're familiar with Bower and you've already decided on the best course of action. Can you provide a simple explanation for me? I'll need something for release notes anyways. I'll release 2.0.1 with the fix today if we can get it all sorted out.
> 
> Also, I'm curious... do we know if this is an issue that just came up with 2.0.0 or has this always been an issue? I wasn't around when the library was created many years ago, but since I started having eyes on it in late 2018, I never noticed anyone mention issues using it with Bower.

Hello @mattwelke,
As pointed out by otoniel in issue # 93, Bower is trying to import the file 'index.js' and the content in it is the same as the link below' https://github.com/schema-inspector/schema-inspector/blob /master/index.js'.

Basically what Bower is doing is what is written in the file 'bower.json' it is importing the file `index.js` in the browser. It turns out that it has the function '
module.exports' which belongs to NodeJS only,
it's the same as you doing this:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <script type="text/javascript" src="https://rawgit.com/caolan/async/master/dist/async.js"></script>
    <script type="text/javascript" src="https://rawgit.com/atinux/schema-inspector/master/index.js"></script>
  </head>

  <body>
    <h1>Schema Inspector</h1>
  </body>
</html>
````

**Comment by ViniciusFXavier** [comment]
> @ViniciusFXavier
> Parece que temos duas alterações. Um está neste PR. Ele move o conteúdo do arquivo JS em lib para index.js, e a mudança que você acabou de descrever parece mudar como index.js importa o arquivo de lib. Se bem entendi, escolheríamos _uma_ dessas alterações, e qualquer uma das alterações faria com que a biblioteca pudesse ser importada pelos usuários do Bower da maneira exata que o README diz a eles, certo?

Exactly my fear with the content of this PR to change things to `index.js` is to break other applications that already use this library and it is not with the locked version.

With the suggestion that I gave you will continue to work both previous versions and new ones.

More realistically, the content in the `index.js` file would be better just like `moment` and `undescore` do, the problem is precisely affecting those who already use it.

**Comment by mattwelke** [comment]
@ViniciusFXavier Nice, I have a decent understanding of the issue now and what we'll do to fix it. @ottonielmatheus thank you sending in this PR but I don't want to fix it by removing the lib file. I don't want people who've followed the readme to install it with Bower to have their setups break (if they were working at any point in the past). I'm going to go with @ViniciusFXavier 's suggestion to improve how index.js detects browser vs. Node.js and how it imports the lib file, so that index.js will always work in browsers. I'll make the change in a separate PR, add some tests with Puppeteer in the CI/CD to assert that the files are usable by the browser directly, and release the fix as 2.0.1. I'll get this done within the next few days.

**Comment by ottonielmatheus** [comment]
@mattwelke  Ok, waiting for fix, thank you guys!!

**Comment by ViniciusFXavier** [comment]
> @ViniciusFXavier Nice, I have a decent understanding of the issue now and what we'll do to fix it. @ottonielmatheus thank you sending in this PR but I don't want to fix it by removing the lib file. I don't want people who've followed the readme to install it with Bower to have their setups break (if they were working at any point in the past). I'm going to go with @ViniciusFXavier 's suggestion to improve how index.js detects browser vs. Node.js and how it imports the lib file, so that index.js will always work in browsers. I'll make the change in a separate PR, add some tests with Puppeteer in the CI/CD to assert that the files are usable by the browser directly, and release the fix as 2.0.1. I'll get this done within the next few days.

@mattwelke I was doing some tests here and I think the best alternative is would be to change both `package.json` and `bower.json`.
Change `"main": "index.js"`, to `"main": "./lib/schema-inspector.js"`.

Because in the lines indicated below they already do the same treatment that I gave as an example for the file `index.js`:
https://github.com/schema-inspector/schema-inspector/blob/e02ea1f68a5db977c8f33a186011142f9d9239ea/lib/schema-inspector.js#L1548-L1553

**Comment by ViniciusFXavier** [comment]
> Parece que há 7 anos, eles mudaram o Bower para usar index.js a fim de corrigir um problema de instalação do Bower na época: [2595511](https://github.com/schema-inspector/schema-inspector/commit/2595511a222ce814579ddecdc4c0d6b8c9575ca1)
> 
> Nós entendemos por que eles fariam isso e por que agora precisamos fazer isso ao contrário para consertar novamente?

Exatamente, 

> It looks like 7 years ago, they actually changed Bower to use index.js in order to fix a Bower install issue back then: [2595511](https://github.com/schema-inspector/schema-inspector/commit/2595511a222ce814579ddecdc4c0d6b8c9575ca1)
> 
> Do we understand why they would have done that and why we now need to do this in reverse to fix it again?

Exactly I saw it too, I just don't understand why they did it.

Lib has not worked properly in browsers for 7 years, you can go back to the version and test. 😞

**Comment by mattwelke** [comment]
I see. Interesting that no one has mentioned this issue in 7 years. I had to admit, I was surprised to see an issue today claiming that the library doesn't work in browsers. We've used it in browsers at my work in production for 4 years. Our workflow is to bundle it in with Webpack. When used in browsers that way, it works perfectly.

I think in 2021, we should actually consider whether Bower support is something we should continue to support going forward. My understanding is that it's an outdated way to build JS applications for browsers. Is this correct?

The example web page already successfully loads the JS file by linking to it with a `<script>` so we know it can be used in browsers directly already:

image

**Comment by ViniciusFXavier** [comment]
> Entendo. Interessante que ninguém mencionou esse assunto em 7 anos. Tive de admitir que fiquei surpreso ao ver um problema hoje, alegando que a biblioteca não funciona em navegadores. Nós o usamos em navegadores no meu trabalho em produção por 4 anos. Nosso fluxo de trabalho é agrupá-lo com o Webpack. Quando usado em navegadores dessa forma, funciona perfeitamente.
> 
> Acho que em 2021, devemos realmente considerar se o apoio do Bower é algo que devemos continuar a apoiar no futuro. Meu entendimento é que é uma maneira desatualizada de construir aplicativos JS para navegadores. Isso está correto?
> 
> A página da web de exemplo já carrega com êxito o arquivo JS vinculando-o a um, `<script>`portanto, sabemos que já pode ser usado diretamente em navegadores:
> 
> imagem

Exatamente o Webpack and Gulp is smart to bundle the `module.exports` but BowerJs not :/

**Comment by ViniciusFXavier** [comment]
Acidental closed

**Comment by ottonielmatheus** [comment]
An alternative to work around the problem is to use bower overrides in bower.json.

image

This solves the problem with the package's index.js, without the need for changes ;)

**Comment by ViniciusFXavier** [comment]
The Webpack is a smart bundler that can solve the modules, Gulp with Bower is not that smart.

Using Bower and Gulp this happens 
image
image

😢

**Comment by ViniciusFXavier** [comment]
> Yeah if I recall, Webpack can follow the `require` statements to find the code it needs to bundle in. I guess the code here was laid out in a flawed way that only flexible module bundlers can work with.
> 
> I don't like the idea of making changes I perceive as dangerous (like editing `main` in `package.json`) because it's very important we don't break anyone's bundling they've already set up. For example, we need to make sure Webpack builds don't break. Many people use Webpack.
> 
> @ottonielmatheus I plan to deprecate support for Bower in the 3.0.0 release that I'll be publishing later this year. Would the workaround you've found satisfy you for now instead of fixing the Bower build? I can add the workaround instructions to the README or merge in this PR if it were changed to just be a README update explaining the workaround.

I don't think it's fair and it doesn't even make sense to discontinue the browser version, since it's just a "mistake" in the way it is exported for previous and new versions.

**Comment by mattwelke** [comment]
@ViniciusFXavier 
> Maybe just ending support for Bower and adding the suggestion of @ottonielmatheus in the documentation is already better.
This is exactly what I'm proposing.

**Comment by mattwelke** [comment]
As a reminder of where we're at right now, we need a PR that involves no changes to how the code is structured and adds instructions to the readme explaining how Bower users can use the library in its current state.

**Review by mattwelke — CHANGES_REQUESTED** [review]
Consensus is to use workaround instead of changing code. Please change PR to only add workaround instructions to README.md

**Pull request closed without merging**
